function [e000, e004, e006] = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [E000, E004, E006] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [E000, E004, E006] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [e000, e004, e006] = importfile("C:\Users\sbansal\Desktop\Circuits\MicroelectronicCircuits\project\Data\Processed\Circuit_Indirect_Bode_80f_p.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-May-2020 03:12:04

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["e000", "e004", "e006"];
opts.VariableTypes = ["double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
e000 = tbl.e000;
e004 = tbl.e004;
e006 = tbl.e006;
end